version: 2

jobs:

    integrate:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox
                ./resources/gcp-install.sh
                gcloud beta emulators pubsub start --project="i3-gcp-proj" &
                tox integrate_tests -vv

    integrate-w-telemetry:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox wipac-mqclient[telemetry]
                ./resources/gcp-install.sh
                gcloud beta emulators pubsub start --project="i3-gcp-proj" &
                tox integrate_tests -vv

    examples:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox
                tox --notest -vv
                . .tox/py/bin/activate
                ./resources/gcp-install.sh
                ./examples/run.sh

    google-examples:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox
                tox --notest -vv
                . .tox/py/bin/activate
                ./resources/gcp-install.sh
                cd ./examples/googles_examples
                ./run-using-emulator.sh


    pycycle:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox pycycle
                tox --notest -vv
                . .tox/py/bin/activate
                pycycle --here --verbose


workflows:
    version: 2
    build_and_test:
        jobs:
            - integrate
            - integrate-w-telemetry
            - examples
            - google-examples
            - pycycle